// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('admin view for guest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('admin view for guest', async function() {
    await driver.get("http://localhost:4200/admin")
    await driver.manage().window().setRect({ width: 989, height: 666 })
    await driver.sleep(1000)
    vars["url"] = await driver.executeScript("return window.location.href;")
    assert(vars["url"].toString() == "http://localhost:4200/")
  })
})
