// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Buy Dishes 2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Buy Dishes 2', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 806, height: 816 })
    await driver.findElement(By.linkText("Zaloguj")).click()
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("patryktest@email.com")
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    await delay(2000);
    await driver.findElement(By.linkText("Menu")).click()
    {
      const element = await driver.findElement(By.linkText("Menu"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move({ origin: element }).perform()
    }
    await delay(2000);
    await driver.findElement(By.linkText("Koszyk")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})

function delay(milliseconds) {
  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}