// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Buy Dishes 2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Buy Dishes 2', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 806, height: 816 })
    await driver.findElement(By.linkText("Zaloguj")).click()
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("patryktest@email.com")
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Menu")).click()
    {
      const element = await driver.findElement(By.linkText("Menu"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".col-sm-6:nth-child(1) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(3) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.linkText("Koszyk(2)")).click()
    await driver.findElement(By.css(".btn-dark")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})
