// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Remove Dishes', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Remove Dishes', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 809, height: 816 })
    await driver.findElement(By.linkText("Zaloguj")).click()
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("patryktest@email.com")
    await driver.findElement(By.id("exampleInputPassword1")).click()
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("test123")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Menu")).click()
  })
})
