// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('successful_register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('successful_register', async function() {
    await driver.get("http://localhost:4200/zarejestruj")
    await driver.manage().window().setRect({ width: 989, height: 666 })
    vars["random_number"] = await driver.executeScript("return String(Math.floor(Math.random()*100000));")
    vars["randomEmail"] = await driver.executeScript("return \'test\'+arguments[0]+\'@test.com\'", vars["random_number"])
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys(vars["randomEmail"])
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("ala123")
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.elementLocated(By.css(".btn-outline-light")), 3000)
    {
      const elements = await driver.findElements(By.css(".btn-outline-light"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".btn-outline-light")).click()
  })
})
