// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test_buying_in_cart', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test_buying_in_cart', async function() {
    await driver.get("http://localhost:4200/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Menu")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(1) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(5) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(6) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(7) .ng-star-inserted > .ng-fa-icon:nth-child(3) path")).click()
    await driver.findElement(By.css(".col-sm-6:nth-child(3) .ng-star-inserted > .ng-fa-icon:nth-child(3) > .svg-inline--fa")).click()
    await driver.findElement(By.linkText("Koszyk(5)")).click()
    await driver.findElement(By.css(".btn-dark")).click()
    await driver.executeScript("window.scrollTo(0,0)")
  })
})
